# Домашня робота №2

## 1 Пароль
Напишіть програму (функцію) для генерування випадкового пароля з такими обмеженнями:
- пароль складається з рівно $10$ символів
- пароль містить хоча б одну маленьку латинську літеру [a-z]
- пароль містить хоча б одну велику латинську літеру [A-Z]
- пароль містить хоча б одну цифру [0-9]
- пароль містить хоча б один спеціальний символ [~!@#$%^&*()-_+=\/{}[].,?<>:;]

In [60]:
import numpy as np
from numpy.random import choice, shuffle
symbols = list('1234567890abcdefghigklmnopqrstuvyxwzABCDEFGHIGKLMNOPQRSTUVYXWZ!@#$%^&*()-=_|/?><~:;{}[]')
digits = list('1234567890')
lower_letters = list('abcdefghigklmnopqrstuvyxwz')
upper_letters = list('ABCDEFGHIGKLMNOPQRSTUVYXWZ')
spec_symbols = list('!@#$%^&*()-=_|/?><~:;{}[]')
shuffle(symbols)
def ran_pass(a = 1, b = 1, c = 1, d = 1, sym = 7, n = 10):
    passw = ''
    A = ''.join(choice(lower_letters, a)) # а - к-сть символів нижнього регістру, які вибираємо випадково
    B = ''.join(choice(upper_letters, b)) # і так далі
    C = ''.join(choice(spec_symbols, c)) #
    D = ''.join(choice(digits, d)) #
    S = ''.join(choice(symbols, sym)) #
    passw = list(A+B+C+D+S)
    shuffle(passw)
    passw = ''.join(passw)
    return passw
#Можна задати параметри, щоб поміняти умову задачі, якщо потрібно, але уважно
print("The random password is:", ran_pass())
    

The random password is: U|zm{3}bwcp


## 2 Герби в ряд
Реалізуйте функцію для обчислення емпіричної та теоретичної імовірностей випадіння $k$ гербів (HEADS) підряд у серії з $n$ підкидань чесної монетки. Підрахуйте відповідні ймовірності для таких параметрів:
- $k = 2, n = 10, 50, 100, 500, 1000, 5000, 10000$
- $k = 3, n = 10, 50, 100, 500, 1000, 5000, 10000$

**Зауваження.** Нехай $k = 2, n = 10$ та маємо таку послідовність результатів підкидання монети: $\{ H, T, H, H, H, H, T, T, H, T \}$. Тоді матимемо $3$ випадки випадіння двох гербів підряд та емпіричну ймовірність такої події $1/3$.

In [264]:
n = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
p = 0.5
for i in n:
    k = 0
    tosses = choice(["H","T"], p=[p,1-p], size=i)
    for i in range(len(tosses)-1):
        if tosses[i] == tosses[i+1] == "H":
            k += 1
    print("n = {}".format(i+2))
    print(tosses)
    print(k)
    print(k/(i-1))
for i in n:
    k = 0
    tosses = choice(["H","T"], p=[p,1-p], size=i)
    for i in range(len(tosses)-2):
        if tosses[i] == tosses[i+1] == tosses[i+2] == "H":
            k += 1
    print("n = {}".format(i+2))
    print(tosses)
    print(k)
    print(k/(i-2))
def task_2(n, k):
    k = 0
    tosses = choice(["H","T"], p = [p, 1-p], size = n)
    iter_tosses = iter(tosses)
    for i in range(n):
        try:
            a = next(iter_tosses)
            if a == "H" and next(iter_tosses) == "H":
                k += 1
        except:
            pass
    print(tosses)
    return k
#
tosses = iter(choice(["H","T"], p = [p, 1-p], size = 10))
print(tosses)
iterator = iter(tosses)
print(next(iterator) == "H")
task_2(10, 2)



n = 10
['H' 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'H' 'H']
1
0.14285714285714285
n = 50
['H' 'H' 'H' 'T' 'H' 'T' 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'T' 'T'
 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'T' 'H' 'H' 'T' 'H' 'H' 'T' 'T'
 'T' 'T' 'T' 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'T' 'T']
4
0.0851063829787234
n = 100
['T' 'T' 'T' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'T'
 'T' 'H' 'H' 'T' 'H' 'H' 'T' 'T' 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'H' 'H'
 'H' 'T' 'T' 'T' 'T' 'T' 'H' 'T' 'H' 'T' 'T' 'T' 'T' 'H' 'H' 'T' 'H' 'T'
 'T' 'T' 'T' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'T' 'H' 'H' 'H' 'T' 'H' 'H' 'T'
 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'H' 'T' 'H' 'T' 'H' 'H' 'T'
 'H' 'H' 'H' 'T' 'T' 'T' 'T' 'T' 'H' 'H']
23
0.23711340206185566
n = 250
['T' 'H' 'T' 'H' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'H' 'H' 'H' 'T' 'H' 'T' 'H'
 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'H' 'T' 'H' 'T'
 'T' 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'T' 'H' 'H' 'T' 'H'
 'T' 'T' 'H' 'H' 'H' 'T' 'H' 'H'

2

## 3 Найбільше число
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що максимальне число після $n$ кидків звичайного грального кубика дорівнює $x\_max$, для таких параметрів:
- $n = 3, x\_max = 6$
- $n = 2, x\_max = 3$
- $n = 3, x\_max = 5$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \max\limits_{1 \leq i \leq n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = x\_max \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Тобто, якщо вводиться $x\_max < 1$ або $x\_max > 6$.

In [176]:
def task_3(n, x_max, all = True):
    try:
        num = choice([1,2,3,4,5,6], n)
        k = list(num).count(x_max)
        if n < 1 or x_max < 1 or x_max > 6:
            return "0"
        if all == True:
            print("n = ", n, "x_max = ", x_max)
            print(num)
            print(k)
            print(k/n)
            print()
        else:
            return k/n
    except Exception:
        print("0")    
task_3(3, 6)
task_3(2, 3)
task_3(3, 5)
questions = [(3, 6), (2, 3), (3, 5)]
for n, x in questions:
    prob = 0 
    for i in range(10000):
        prob += task_3(n, x, False)
    emp_prob = prob/10000
    print("n = 10000, x_max = {}".format(x))
    print(emp_prob)
task_3(0, 5)



n =  3 x_max =  6
[1 3 2]
0
0.0

n =  2 x_max =  3
[3 1]
1
0.5

n =  3 x_max =  5
[3 2 1]
0
0.0

n = 10000, x_max = 6
0.16606666666666142
n = 10000, x_max = 3
0.1656
n = 10000, x_max = 5
0.16329999999999487


'0'

## 4 Сума чисел
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що сума чисел після $n$ кидків звичайного грального кубика дорівнює $s$, для таких параметрів:
- $n = 3, s = 13$
- $n = 2, s = 5$
- $n = 3, s = 7$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \sum\limits_{i = 1}^{n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = s \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Наприклад, якщо при $n = 3$ вводиться $s < 3$ або $s > 18$.

In [177]:
def task_4(n, s, all = True):
    try:
        k = 0
        num = choice([1,2,3,4,5,6], n)
        if (n < 1) or (n == 1 and (s < 1 or s > 6)) or (n == 2 and (s < 1 or s > 12)) or (n == 3 and (s < 1 or s > 18)):
            return "0"
        summ = sum(num)
        if all == True:
            print("n = ", n, "s = ", s)
            print(num)
            print(k)
            print("sum = ", summ)
            print()
        else:
            return summ
    except Exception:
        print("0")
task_4(3, 6)
task_4(2, 3)
task_4(3, 5)
questions = [(3, 13), (2, 5), (3, 7)]
for n, s in questions:
    prob = 0 
    emp_prob = 0
    for i in range(10000):
        if task_4(n, s, False) == s:
            prob += 1
    emp_prob = prob/10000
    print("tests = 10000, n = {}, s = {}".format(n, s))
    print(emp_prob)
task_4(0, 5)




n =  3 s =  6
[6 1 6]
0
sum =  13

n =  2 s =  3
[1 2]
0
sum =  3

n =  3 s =  5
[6 1 6]
0
sum =  13

tests = 10000, n = 3, s = 13
0.1001
tests = 10000, n = 2, s = 5
0.1171
tests = 10000, n = 3, s = 7
0.0672


'0'